name: SkyblockPlugin
version: 1.0
main: com.example.skyblock.SkyblockPlugin
api-version: 1.20
commands:
  island:
    description: "Gestisci la tua isola Skyblock."
  quest:
    description: "Visualizza e completa le missioni."
  balance:
    description: "Mostra il saldo economico del giocatore."
  leaderboard:
    description: "Visualizza la classifica dei migliori giocatori."
